### ISSUE TITLE
Choose a name for the project

### ISSUE THREAD

**Issue by anbenson** [googleinterns/step1-2020#2]
The project name should be clearly shown in the README.md file. If desired, you can also change the name of the repository.

Other files that need to be updated with the project name:
- pom.xml: YOUR_PROJECT_NAME_HERE should be replaced with the project name
- src/main/java/com/google/step/YOUR_PROJECT_NAME_HERE should be replaced with the project name
- HomepageServlet.java: the package needs to be updated to match above
- SearchServlet.java: the package needs to be updated to match above

**Comment by kaylaleung** [comment]
@anbenson I don't think we have permissions to change the repository name

**Comment by anbenson** [comment]
I'm thinking maybe keep the repo name as-is for consistency (also because I can't find the place where it said you can change the repo name). But let's put something in the README?

**Comment by kaylaleung** [comment]
Resolved in #24
