### ISSUE TITLE
500 on http://localhost:8080/search?q=code

### ISSUE THREAD

**Issue by anbenson** [googleinterns/step1-2020#23]
When I go to http://localhost:8080/search?q=code, I immediately hit a 500 internal server error. (You can also to the homepage and type something in like "code".)

This is freshly cloned, freshly built from master.

Error:

URI: | /search
-- | --
500
org.json.JSONException: JSONObject["items"] not found.
com.google.step.snippet.servlets.SearchServlet
org.json.JSONException: JSONObject["items"] not found.

**Comment by kaylaleung** [comment]
There don't seem to be any issues running on master or #18. Also did you perhaps not run with inserted keys? That's caused 500 errors for me in the past.

**Comment by anbenson** [comment]
Oops, of course. Could we add a Setup section to the README? The `maven package appengine:run` part could be the last part of the setup.
