### ISSUE TITLE
Create a shared "Client" interface for W3School, StackOverflow, and GeeksForGeeks clients.

### ISSUE THREAD

**Issue by joanchenx** [googleinterns/step1-2020#26]
Details in comment: https://github.com/googleinterns/step1-2020/pull/19#discussion_r453908486

**Comment by irisliu77** [comment]
done

**Comment by anbenson** [comment]
Let's close issues when master is updated e.g. when #33 is merged.

**Comment by irisliu77** [comment]
#33 merged
