### ISSUE TITLE
HTML code snippet not being displayed on SRP

### ISSUE THREAD

**Issue by kaylaleung** [googleinterns/step1-2020#28]
When querying "html img" the card from W3School should be displaying 

`<img src="img_girl.jpg" alt="Girl in a jacket" width="500" height="600">`

from [https://www.w3schools.com/tags/tag_img.asp](https://www.w3schools.com/tags/tag_img.asp) since `<img src="img_girl.jpg" alt="Girl in a jacket" width="500" height="600">` is stored as a string in the card class in the code field. 

But instead in #27 , it's rendering the HTML code completely and only a small image icon is displayed instead.

**Comment by AaronLopes** [comment]
addressed in #27
