### ISSUE TITLE
Abrupt description cutoff on StackOverflow cards

### ISSUE THREAD

**Issue by kaylaleung** [googleinterns/step1-2020#38]
In #13 , the max description length for StackOverflow cards is 200 characters.  When the descriptions are displayed on the cards on SRP in #27 it looks like a bug where the description is randomly cut off mid-sentence at the 200 character mark.

Should be fixed with some appended `...` or _`(see more)`_ to the description field.

Note - Potentially might be something to be fixed on W3Schools and GeeksForGeeks also if description lengths get too long.

**Comment by irisliu77** [comment]
i think this can potentially be done in the card constructor. don't really need to deal with it separately in each clients.

**Comment by irisliu77** [comment]
'...'  added

**Comment by irisliu77** [comment]
this is solved in #27
