### ISSUE TITLE
500 Error JsonException from StackOverflow Client

### ISSUE THREAD

**Issue by kaylaleung** [googleinterns/step1-2020#39]
When querying for `https://www.w3schools.com/html/html_quotation_elements.asp` in the search box, the redirect link 
`/search?q=https%3A%2F%2Fwww.w3schools.com%2Fhtml%2Fhtml_quotation_elements.asp`throws a HTTP ERROR 500 org.json.JSONException: JSONArray[0] not found from the StackOverflow Client

_At least I'm pretty sure it's StackOverflow Client since when I comment out the StackOverflow .search code this error doesn't appear_

**Comment by irisliu77** [comment]
this because the CSE returns an Stackoverflow question that is not answered yet. need to be resolved in future pr.

**Comment by irisliu77** [comment]
#54
