### ISSUE TITLE
Determine a solution to the HTML escaping issue

### ISSUE THREAD

**Issue by anbenson** [googleinterns/step1-2020#44]
Currently HTML in Cards is not escaped. This brings a couple issues.
- This leaves the application open to Cross-Site Scripting attacks. If code scraped into the cards contains JavaScript, such untrusted code would automatically run on the user's computer.
- HTML example code is rendered as HTML instead of code that the user can see.

However it's not as simple as just escaping all HTML we see. Doing so shows the user unrendered HTML which can be confusing and hard to read. Stripping HTML in some cases might be a good idea.

**Comment by irisliu77** [comment]
for stackoverflow, i don't see the need of escaping html, it's in the correct format #63

**Comment by anbenson** [comment]
For posterity, here's what we decided in today's meeting (feel free to correct if I'm wrong):
1) Remove the 200 or 300 character limit in the cards. (Higher priority because doing so will avoid some of the merged-cards issues we're seeing.)
- Sanitize cards with jsoup.clean
- Give cards an initial width and height, and allow them to be scrolled horizontally and vertically

**Comment by anbenson** [comment]
One last thing - for cards about HTML code, we might have to escape instead.
