### ISSUE TITLE
Code + description sections get split off in SO card

### ISSUE THREAD

**Issue by kaylaleung** [googleinterns/step1-2020#51]
The text and code responses for StackOverflow, since they are somewhat "mixed media" responses contained within a single answer, get split up weirdly in a way that's not readable continuously.

See SO card for "how to access address of a pointer" query

**Comment by irisliu77** [comment]
i realize this issue but cannot think of a universal solution to different query

**Comment by kaylaleung** [comment]
Inspiration: https://duckduckgo.com/?q=get+pointer+address&t=ffab&ia=web&iax=qa. Perhaps just integrate the code and description blocks together

**Comment by irisliu77** [comment]
> Inspiration: https://duckduckgo.com/?q=get+pointer+address&t=ffab&ia=web&iax=qa. Perhaps just integrate the code and description blocks together

same thought here, done in #63
