### ISSUE TITLE
base.tag is 2-tab-tabbed instead of 2-space-tabbed

### ISSUE THREAD

**Issue by anbenson** [googleinterns/step1-2020#71]
https://github.com/googleinterns/step1-2020/blob/master/src/main/webapp/WEB-INF/tags/base.tag

compare to https://github.com/googleinterns/step1-2020/blob/master/src/main/webapp/WEB-INF/templates/homepage.jsp

**Comment by kaylaleung** [comment]
Fixed in #59

**Comment by anbenson** [comment]
Let's not close until fixed in master
